name: Kubescape scanning for image vulnerabilities
on: [push, pull_request]
jobs:
  kubescape-scan-image:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
    - uses: actions/checkout@v3
    - uses: kubescape/github-action@feat-image-scanning
      with:
        image: "quay.io/kubescape/kubescape"
        format: "pretty-printer"
        # # Username for a private registry with the image
        # registryUsername: ${{secrets.KUBESCAPE_REGISTRY_USERNAME}}
        # # Password for a private registry with the image
        # registryPassword: ${{secrets.KUBESCAPE_REGISTRY_PASSWORD}}
        # # Fail at or above the specified vulnerability severity threshold
        # severityThreshold: "critical"
        # Kubescape cloud account ID
        # account: ${{secrets.KUBESCAPE_ACCOUNT}}
